### ISSUE TITLE
Unable to correctly load TIFF files into amfbrowser

### ISSUE THREAD

**Issue by LorenzoJW** [SchornacklabSLCU/amfinder#21]
Hello, 

I have installed amf & amfbrowser on mac. When choosing files to upload for annotation, I am unable to load TIFF files correctly into the browser. After converting the file into jpeg it uploads correctly. I have attached an image of what an uploaded TIFF file looks like (when experiencing the error) & [this link](https://drive.google.com/drive/folders/1vUkKalShvAvxpuuip4LkpDNxmld9EsTH?usp=sharing) will take you to a drive folder with the jpeg & tiff versions of the image used. 

Thank you for your time,
![image](https://user-images.githubusercontent.com/99298244/154603004-591d5435-3794-42c1-ad4b-da891938649d.png)

**Comment by EEvangelisti** [comment]
Hello,

Thanks for reporting this. I am able to reproduce the bug on Linux. This is due to a problem with transparency. I modified the code accordingly. Please re-download the repository and recompile `amfbrowser`. Do not use the MacOS-Catilina binary which is still the old version. Your install of `amf` is not affected.

Please let me know if that works for you.

Best regards,
Edouard
